//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mayinTarlasi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCTestEntities2 : DbContext
    {
        public MVCTestEntities2()
            : base("name=MVCTestEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PublicMessenger> PublicMessengers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBLgameData> TBLgameDatas { get; set; }
        public virtual DbSet<TBLuserData> TBLuserDatas { get; set; }
        public virtual DbSet<PersonelMessage> PersonelMessages { get; set; }
    }
}
