//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mayinTarlasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicMessenger
    {
        public int ID { get; set; }
        public int SenderID { get; set; }
        public string SenderName { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Senddate { get; set; }
    
        public virtual TBLgameData TBLgameData { get; set; }
        public virtual TBLuserData TBLuserData { get; set; }
    }
}
