//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mayinTarlasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLgameData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLgameData()
        {
            this.PublicMessengers = new HashSet<PublicMessenger>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> flagsUsed { get; set; }
        public Nullable<int> Time { get; set; }
        public int Try { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicMessenger> PublicMessengers { get; set; }
        public virtual TBLuserData TBLuserData { get; set; }
    }
}
